"""add office_days_per_week and min_experience_years to role

Revision ID: db3bd3223260
Revises: 03fc7897048b
Create Date: 2026-03-02 14:23:34.356276

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'db3bd3223260'
down_revision: str | Sequence[str] | None = '03fc7897048b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('office_days_per_week', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('min_experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'min_experience_years')
    op.drop_column('role', 'office_days_per_week')
    # ### end Alembic commands ###
